spring:
  application:
    name: book-marketplace
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
jwt:
  secret: w9I+UjRz8cBn2D9LbxuJVoMYlVzMZ8T3wSpATrdB9Vo=
  expiration-ms: 900000
