spring:
  application:
    name: book-marketplace
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bookmarketplace?createDatabaseIfNoExist=true
    username: root
    password: password
  jackson:
    default-property-inclusion: non_null
